bandList = ['geometry', 'B11_amp', 'B11_max', 'B11_mean', 'B11_min',
       'B11_phase', 'B11_phase2', 'B11_phase3', 'B11_rmse', 'B11_slope',
       'B12_amp', 'B12_max', 'B12_mean', 'B12_min', 'B12_phase',
       'B12_phase2', 'B12_phase3', 'B12_rmse', 'B12_slope', 'B2_amp',
       'B2_max', 'B2_mean', 'B2_min', 'B2_phase', 'B2_phase2',
       'B2_phase3', 'B2_rmse', 'B2_slope', 'B3_amp', 'B3_max', 'B3_mean',
       'B3_min', 'B3_phase', 'B3_phase2', 'B3_phase3', 'B3_rmse',
       'B3_slope', 'B4_amp', 'B4_max', 'B4_mean', 'B4_min', 'B4_phase',
       'B4_phase2', 'B4_phase3', 'B4_rmse', 'B4_slope', 'B5_amp',
       'B5_max', 'B5_mean', 'B5_min', 'B5_phase', 'B5_phase2',
       'B5_phase3', 'B5_rmse', 'B5_slope', 'B6_amp', 'B6_max', 'B6_mean',
       'B6_min', 'B6_phase', 'B6_phase2', 'B6_phase3', 'B6_rmse',
       'B6_slope', 'B7_amp', 'B7_max', 'B7_mean', 'B7_min', 'B7_phase',
       'B7_phase2', 'B7_phase3', 'B7_rmse', 'B7_slope', 'B8A_amp',
       'B8A_max', 'B8A_mean', 'B8A_min', 'B8A_phase', 'B8A_phase2',
       'B8A_phase3', 'B8A_rmse', 'B8A_slope', 'B8_amp', 'B8_max',
       'B8_mean', 'B8_min', 'B8_phase', 'B8_phase2', 'B8_phase3',
       'B8_rmse', 'B8_slope', 'VH_amp', 'VH_max', 'VH_mean', 'VH_min',
       'VH_phase', 'VH_phase2', 'VH_phase3', 'VH_rmse', 'VH_slope',
       'VV_amp', 'VV_max', 'VV_mean', 'VV_min', 'VV_phase', 'VV_phase2',
       'VV_phase3', 'VV_rmse', 'VV_slope', 'aspect', 'elevation',
       'hillshade', 'idx', 'lat', 'lon', 'ndvi_amp', 'ndvi_max', 'ndvi_mean',
       'ndvi_min', 'ndvi_phase', 'ndvi_phase2', 'ndvi_phase3',
       'ndvi_rmse', 'ndvi_slope', 'ndwi_amp', 'ndwi_max', 'ndwi_mean',
       'ndwi_min', 'ndwi_phase', 'ndwi_phase2', 'ndwi_phase3',
       'ndwi_rmse', 'ndwi_slope', 'rem', 'slope', 'twi', 'water_amp',
       'water_amp_s1', 'water_max', 'water_max_s1', 'water_mean',
       'water_mean_s1', 'water_min', 'water_min_s1', 'water_phase',
       'water_phase2', 'water_phase2_s1', 'water_phase3',
       'water_phase3_s1', 'water_phase_s1', 'water_rmse', 'water_rmse_s1',
       'water_slope', 'water_slope_s1', 'wetland_label', 'wetland_mask',
       'world_cover']