
#%%

fused_class_dict = {
    # wetland types
    0: "Transformed wetlands",
    1: "Varzeas and/or Igapós",
    2: "Wetlands in small depressions", # supplied by rain and/or floodable or waterlogged savannas and/or Zurales and/or estuaries
    3: "Flooded forests",
    4: "Overflow Forests",
    5: "Interfluvial flooded forests",
    6: "Floodable grasslands",
    7: "Rivers",
    8: "Wetlands in the process of transformation",
    9: "Swamps",

    # world cover 10m
    10: "tree cover",
    11: "Mangroves",
    12: "Shrubland",
    13: "Grassland",
    14: "Cropland", # supplied by rain and/or floodable or waterlogged savannas and/or Zurales and/or estuaries
    15: "Built-up",
    16: "Bare/sparse vegetation",
    17: "Snow and ice",
    18: "Permanent water", # same class as 7: Rivers? does this include other types of permanent water? #TODO confirm?
    19: "Herbaceour wetland",
    20: "Moss and lichen"
}

rmse_bands = ['B11_rmse',
 'B12_rmse',
 'B2_rmse',
 'B3_rmse',
 'B4_rmse',
 'B5_rmse',
 'B6_rmse',
 'B7_rmse',
 'B8A_rmse',
 'B8_rmse',
 'HH_rmse',
 'HV_rmse',
 'VH_rmse',
 'VV_rmse',
 'ndvi_rmse',
 'ndwi_rmse',
 'water_rmse',
 'water_rmse_s1']

bandList = [
    'B11_COS',
    'B11_COS2',
    'B11_COS3',
    'B11_INTP',
    'B11_SIN',
    'B11_SIN2',
    'B11_SIN3',
    'B11_SLP',
    'B11_amp',
    'B11_apr',
    'B11_jul',
    'B11_max',
    'B11_mean',
    'B11_min',
    'B11_oct',
    'B11_phase',
    'B11_phase2',
    'B11_phase3',
    'B12_COS',
    'B12_COS2',
    'B12_COS3',
    'B12_INTP',
    'B12_SIN',
    'B12_SIN2',
    'B12_SIN3',
    'B12_SLP',
    'B12_amp',
    'B12_apr',
    'B12_jul',
    'B12_max',
    'B12_mean',
    'B12_min',
    'B12_oct',
    'B12_phase',
    'B12_phase2',
    'B12_phase3',
    'B2_COS',
    'B2_COS2',
    'B2_COS3',
    'B2_INTP',
    'B2_SIN',
    'B2_SIN2',
    'B2_SIN3',
    'B2_SLP',
    'B2_amp',
    'B2_apr',
    'B2_jul',
    'B2_max',
    'B2_mean',
    'B2_min',
    'B2_oct',
    'B2_phase',
    'B2_phase2',
    'B2_phase3',
    'B3_COS',
    'B3_COS2',
    'B3_COS3',
    'B3_INTP',
    'B3_SIN',
    'B3_SIN2',
    'B3_SIN3',
    'B3_SLP',
    'B3_amp',
    'B3_apr',
    'B3_jul',
    'B3_max',
    'B3_mean',
    'B3_min',
    'B3_oct',
    'B3_phase',
    'B3_phase2',
    'B3_phase3',
    'B4_COS',
    'B4_COS2',
    'B4_COS3',
    'B4_INTP',
    'B4_SIN',
    'B4_SIN2',
    'B4_SIN3',
    'B4_SLP',
    'B4_amp',
    'B4_apr',
    'B4_jul',
    'B4_max',
    'B4_mean',
    'B4_min',
    'B4_oct',
    'B4_phase',
    'B4_phase2',
    'B4_phase3',
    'B5_COS',
    'B5_COS2',
    'B5_COS3',
    'B5_INTP',
    'B5_SIN',
    'B5_SIN2',
    'B5_SIN3',
    'B5_SLP',
    'B5_amp',
    'B5_apr',
    'B5_jul',
    'B5_max',
    'B5_mean',
    'B5_min',
    'B5_oct',
    'B5_phase',
    'B5_phase2',
    'B5_phase3',
    'B6_COS',
    'B6_COS2',
    'B6_COS3',
    'B6_INTP',
    'B6_SIN',
    'B6_SIN2',
    'B6_SIN3',
    'B6_SLP',
    'B6_amp',
    'B6_apr',
    'B6_jul',
    'B6_max',
    'B6_mean',
    'B6_min',
    'B6_oct',
    'B6_phase',
    'B6_phase2',
    'B6_phase3',
    'B7_COS',
    'B7_COS2',
    'B7_COS3',
    'B7_INTP',
    'B7_SIN',
    'B7_SIN2',
    'B7_SIN3',
    'B7_SLP',
    'B7_amp',
    'B7_apr',
    'B7_jul',
    'B7_max',
    'B7_mean',
    'B7_min',
    'B7_oct',
    'B7_phase',
    'B7_phase2',
    'B7_phase3',
    'B8A_COS',
    'B8A_COS2',
    'B8A_COS3',
    'B8A_INTP',
    'B8A_SIN',
    'B8A_SIN2',
    'B8A_SIN3',
    'B8A_SLP',
    'B8A_amp',
    'B8A_apr',
    'B8A_jul',
    'B8A_max',
    'B8A_mean',
    'B8A_min',
    'B8A_oct',
    'B8A_phase',
    'B8A_phase2',
    'B8A_phase3',
    'B8_COS',
    'B8_COS2',
    'B8_COS3',
    'B8_INTP',
    'B8_SIN',
    'B8_SIN2',
    'B8_SIN3',
    'B8_SLP',
    'B8_amp',
    'B8_apr',
    'B8_jul',
    'B8_max',
    'B8_mean',
    'B8_min',
    'B8_oct',
    'B8_phase',
    'B8_phase2',
    'B8_phase3',
    'BIOME_NUM',
    'ECO_ID',
    'HH_COS',
    'HH_COS2',
    'HH_COS3',
    'HH_INTP',
    'HH_SIN',
    'HH_SIN2',
    'HH_SIN3',
    'HH_SLP',
    'HH_amp',
    'HH_apr',
    'HH_jul',
    'HH_max',
    'HH_mean',
    'HH_min',
    'HH_oct',
    'HH_phase',
    'HH_phase2',
    'HH_phase3',
    'HV_COS',
    'HV_COS2',
    'HV_COS3',
    'HV_INTP',
    'HV_SIN',
    'HV_SIN2',
    'HV_SIN3',
    'HV_SLP',
    'HV_amp',
    'HV_apr',
    'HV_jul',
    'HV_max',
    'HV_mean',
    'HV_min',
    'HV_oct',
    'HV_phase',
    'HV_phase2',
    'HV_phase3',
    'VH_COS',
    'VH_COS2',
    'VH_COS3',
    'VH_INTP',
    'VH_SIN',
    'VH_SIN2',
    'VH_SIN3',
    'VH_SLP',
    'VH_amp',
    'VH_apr',
    'VH_jul',
    'VH_max',
    'VH_mean',
    'VH_min',
    'VH_oct',
    'VH_phase',
    'VH_phase2',
    'VH_phase3',
    'VV_COS',
    'VV_COS2',
    'VV_COS3',
    'VV_INTP',
    'VV_SIN',
    'VV_SIN2',
    'VV_SIN3',
    'VV_SLP',
    'VV_amp',
    'VV_apr',
    'VV_jul',
    'VV_max',
    'VV_mean',
    'VV_min',
    'VV_oct',
    'VV_phase',
    'VV_phase2',
    'VV_phase3',
    'aspect',
    'canopy_height',
    'canopy_height_std',
    'chirps_precip',
    'elevation',
    'era5_precip',
    'hand30_100',
    'hand30_1000',
    'hillshade',
    'ndvi_COS',
    'ndvi_COS2',
    'ndvi_COS3',
    'ndvi_INTP',
    'ndvi_SIN',
    'ndvi_SIN2',
    'ndvi_SIN3',
    'ndvi_SLP',
    'ndvi_amp',
    'ndvi_apr',
    'ndvi_jul',
    'ndvi_max',
    'ndvi_mean',
    'ndvi_min',
    'ndvi_oct',
    'ndvi_phase',
    'ndvi_phase2',
    'ndvi_phase3',
    'ndwi_COS',
    'ndwi_COS2',
    'ndwi_COS3',
    'ndwi_INTP',
    'ndwi_SIN',
    'ndwi_SIN2',
    'ndwi_SIN3',
    'ndwi_SLP',
    'ndwi_amp',
    'ndwi_apr',
    'ndwi_jul',
    'ndwi_max',
    'ndwi_mean',
    'ndwi_min',
    'ndwi_oct',
    'ndwi_phase',
    'ndwi_phase2',
    'ndwi_phase3',
    'rem',
    'slope',
    'soil_water_0',
    'soil_water_10',
    'soil_water_100',
    'soil_water_200',
    'soil_water_30',
    'soil_water_60',
    'twi',
    'water_COS',
    'water_COS2',
    'water_COS2_s1',
    'water_COS3',
    'water_COS3_s1',
    'water_COS_s1',
    'water_INTP',
    'water_INTP_s1',
    'water_SIN',
    'water_SIN2',
    'water_SIN2_s1',
    'water_SIN3',
    'water_SIN3_s1',
    'water_SIN_s1',
    'water_SLP',
    'water_SLP_s1',
    'water_amp',
    'water_amp_s1',
    'water_apr',
    'water_apr_s1',
    'water_jul',
    'water_jul_s1',
    'water_max',
    'water_max_s1',
    'water_mean',
    'water_mean_s1',
    'water_min',
    'water_min_s1',
    'water_oct',
    'water_oct_s1',
    'water_phase',
    'water_phase2',
    'water_phase2_s1',
    'water_phase3',
    'water_phase3_s1',
    'water_phase_s1'
]



high_rank_bands = [
       'rem', 'elevation', 'hand30_100', 'ECO_ID', 'chirps_precip',
       'hand30_1000', 'era5_precip', 'BIOME_NUM', 'twi', 'B11_oct',
       'slope', 'B11_phase2', 'canopy_height', 'HV_INTP', 'HH_phase',
       'B8_apr', 'HH_amp', 'B12_apr', 'HV_apr', 'ndwi_oct', 'ndwi_apr',
       'B8_jul', 'B3_jul', 'B3_apr', 'B2_oct', 'B3_oct', 'B12_jul',
       'B4_jul', 'B4_apr', 'B2_jul', 'B2_apr', 'B11_jul', 'B11_apr',
       'B12_oct', 'B8A_jul', 'B4_oct', 'B7_INTP', 'B6_apr', 'B6_jul',
       'B6_oct', 'B5_apr', 'B5_jul', 'B5_oct', 'hillshade', 'B8A_INTP',
       'B8A_oct', 'B8_INTP', 'B8A_apr', 'B7_apr', 'B7_jul', 'B7_oct',
       'ndwi_jul', 'water_apr', 'ndvi_apr', 'VV_INTP', 'B8_oct',
       'HH_INTP', 'HH_apr', 'HH_jul', 'HH_max', 'VH_INTP', 'VV_oct',
       'ndvi_jul', 'VV_apr', 'VV_jul', 'VH_oct', 'VH_jul', 'VH_mean',
       'VH_apr', 'HH_oct', 'HV_oct', 'HV_jul', 
       # 'aspect', 'soil_water_100',
       # 'water_INTP', 'soil_water_60', 'soil_water_30', 'water_oct_s1',
       # 'water_oct', 'water_jul_s1', 'water_jul', 'water_apr_s1',
       # 'soil_water_200', 'soil_water_10', 'soil_water_0', 'ndvi_oct',
       # 'B6_INTP'
]


S1_bands = ['VH_COS',
 'VH_COS2',
 'VH_COS3',
 'VH_INTP',
 'VH_SIN',
 'VH_SIN2',
 'VH_SIN3',
 'VH_SLP',
 'VH_amp',
 'VH_apr',
 'VH_jul',
 'VH_max',
 'VH_mean',
 'VH_min',
 'VH_oct',
 'VH_phase',
 'VH_phase2',
 'VH_phase3',
 'VV_COS',
 'VV_COS2',
 'VV_COS3',
 'VV_INTP',
 'VV_SIN',
 'VV_SIN2',
 'VV_SIN3',
 'VV_SLP',
 'VV_amp',
 'VV_apr',
 'VV_jul',
 'VV_max',
 'VV_mean',
 'VV_min',
 'VV_oct',
 'VV_phase',
 'VV_phase2',
 'VV_phase3',
 'water_COS2_s1',
 'water_COS3_s1',
 'water_COS_s1',
 'water_INTP_s1',
 'water_SIN2_s1',
 'water_SIN3_s1',
 'water_SIN_s1',
 'water_SLP_s1',
 'water_amp_s1',
 'water_apr_s1',
 'water_jul_s1',
 'water_max_s1',
 'water_mean_s1',
 'water_min_s1',
 'water_oct_s1',
 'water_phase2_s1',
 'water_phase3_s1',
 'water_phase_s1']

SS_bands = ['HH_COS',
 'HH_COS2',
 'HH_COS3',
 'HH_INTP',
 'HH_SIN',
 'HH_SIN2',
 'HH_SIN3',
 'HH_SLP',
 'HH_amp',
 'HH_apr',
 'HH_jul',
 'HH_max',
 'HH_mean',
 'HH_min',
 'HH_oct',
 'HH_phase',
 'HH_phase2',
 'HH_phase3',
 'HV_COS',
 'HV_COS2',
 'HV_COS3',
 'HV_INTP',
 'HV_SIN',
 'HV_SIN2',
 'HV_SIN3',
 'HV_SLP',
 'HV_amp',
 'HV_apr',
 'HV_jul',
 'HV_max',
 'HV_mean',
 'HV_min',
 'HV_oct',
 'HV_phase',
 'HV_phase2',
 'HV_phase3']


S2_bands = ['B11_COS',
 'B11_COS2',
 'B11_COS3',
 'B11_INTP',
 'B11_SIN',
 'B11_SIN2',
 'B11_SIN3',
 'B11_SLP',
 'B11_amp',
 'B11_apr',
 'B11_jul',
 'B11_max',
 'B11_mean',
 'B11_min',
 'B11_oct',
 'B11_phase',
 'B11_phase2',
 'B11_phase3',
 'B12_COS',
 'B12_COS2',
 'B12_COS3',
 'B12_INTP',
 'B12_SIN',
 'B12_SIN2',
 'B12_SIN3',
 'B12_SLP',
 'B12_amp',
 'B12_apr',
 'B12_jul',
 'B12_max',
 'B12_mean',
 'B12_min',
 'B12_oct',
 'B12_phase',
 'B12_phase2',
 'B12_phase3',
 'B2_COS',
 'B2_COS2',
 'B2_COS3',
 'B2_INTP',
 'B2_SIN',
 'B2_SIN2',
 'B2_SIN3',
 'B2_SLP',
 'B2_amp',
 'B2_apr',
 'B2_jul',
 'B2_max',
 'B2_mean',
 'B2_min',
 'B2_oct',
 'B2_phase',
 'B2_phase2',
 'B2_phase3',
 'B3_COS',
 'B3_COS2',
 'B3_COS3',
 'B3_INTP',
 'B3_SIN',
 'B3_SIN2',
 'B3_SIN3',
 'B3_SLP',
 'B3_amp',
 'B3_apr',
 'B3_jul',
 'B3_max',
 'B3_mean',
 'B3_min',
 'B3_oct',
 'B3_phase',
 'B3_phase2',
 'B3_phase3',
 'B4_COS',
 'B4_COS2',
 'B4_COS3',
 'B4_INTP',
 'B4_SIN',
 'B4_SIN2',
 'B4_SIN3',
 'B4_SLP',
 'B4_amp',
 'B4_apr',
 'B4_jul',
 'B4_max',
 'B4_mean',
 'B4_min',
 'B4_oct',
 'B4_phase',
 'B4_phase2',
 'B4_phase3',
 'B5_COS',
 'B5_COS2',
 'B5_COS3',
 'B5_INTP',
 'B5_SIN',
 'B5_SIN2',
 'B5_SIN3',
 'B5_SLP',
 'B5_amp',
 'B5_apr',
 'B5_jul',
 'B5_max',
 'B5_mean',
 'B5_min',
 'B5_oct',
 'B5_phase',
 'B5_phase2',
 'B5_phase3',
 'B6_COS',
 'B6_COS2',
 'B6_COS3',
 'B6_INTP',
 'B6_SIN',
 'B6_SIN2',
 'B6_SIN3',
 'B6_SLP',
 'B6_amp',
 'B6_apr',
 'B6_jul',
 'B6_max',
 'B6_mean',
 'B6_min',
 'B6_oct',
 'B6_phase',
 'B6_phase2',
 'B6_phase3',
 'B7_COS',
 'B7_COS2',
 'B7_COS3',
 'B7_INTP',
 'B7_SIN',
 'B7_SIN2',
 'B7_SIN3',
 'B7_SLP',
 'B7_amp',
 'B7_apr',
 'B7_jul',
 'B7_max',
 'B7_mean',
 'B7_min',
 'B7_oct',
 'B7_phase',
 'B7_phase2',
 'B7_phase3',
 'B8A_COS',
 'B8A_COS2',
 'B8A_COS3',
 'B8A_INTP',
 'B8A_SIN',
 'B8A_SIN2',
 'B8A_SIN3',
 'B8A_SLP',
 'B8A_amp',
 'B8A_apr',
 'B8A_jul',
 'B8A_max',
 'B8A_mean',
 'B8A_min',
 'B8A_oct',
 'B8A_phase',
 'B8A_phase2',
 'B8A_phase3',
 'B8_COS',
 'B8_COS2',
 'B8_COS3',
 'B8_INTP',
 'B8_SIN',
 'B8_SIN2',
 'B8_SIN3',
 'B8_SLP',
 'B8_amp',
 'B8_apr',
 'B8_jul',
 'B8_max',
 'B8_mean',
 'B8_min',
 'B8_oct',
 'B8_phase',
 'B8_phase2',
 'B8_phase3',
 'ndvi_COS',
 'ndvi_COS2',
 'ndvi_COS3',
 'ndvi_INTP',
 'ndvi_SIN',
 'ndvi_SIN2',
 'ndvi_SIN3',
 'ndvi_SLP',
 'ndvi_amp',
 'ndvi_apr',
 'ndvi_jul',
 'ndvi_max',
 'ndvi_mean',
 'ndvi_min',
 'ndvi_oct',
 'ndvi_phase',
 'ndvi_phase2',
 'ndvi_phase3',
 'ndwi_COS',
 'ndwi_COS2',
 'ndwi_COS3',
 'ndwi_INTP',
 'ndwi_SIN',
 'ndwi_SIN2',
 'ndwi_SIN3',
 'ndwi_SLP',
 'ndwi_amp',
 'ndwi_apr',
 'ndwi_jul',
 'ndwi_max',
 'ndwi_mean',
 'ndwi_min',
 'ndwi_oct',
 'ndwi_phase',
 'ndwi_phase2',
 'ndwi_phase3',
 'water_COS',
 'water_COS2',
 'water_COS3',
 'water_INTP',
 'water_SIN',
 'water_SIN2',
 'water_SIN3',
 'water_SLP',
 'water_amp',
 'water_apr',
 'water_jul',
 'water_max',
 'water_mean',
 'water_min',
 'water_oct',
 'water_phase',
 'water_phase2',
 'water_phase3']

S2_bands_selected = ['B11_jul',
 'B12_jul',
 'B12_oct',
 'B2_jul',
 'B11_oct',
 'B8_oct',
 'B2_apr',
 'B5_apr',
 'B5_jul',
 'ndwi_oct',
 'B4_apr',
 'B6_phase',
 'water_oct',
 'ndvi_oct',
 'B7_apr',
 'B8A_phase',
 'B12_phase',
 'B2_phase',
 'B11_apr',
 'B12_apr',
 'ndvi_phase',
 'B6_apr',
 'B6_oct',
 'B2_INTP',
 'B2_oct',
 'B11_INTP',
 'B11_phase',
 'B12_INTP',
 'B4_oct',
 'B3_apr',
 'B3_jul',
 'B5_oct',
 'B6_INTP',
 'B6_jul',
 'B5_INTP',
 'B3_oct',
 'B4_jul',
 'ndvi_apr',
 'ndvi_jul',
 'B8A_INTP',
 'ndvi_INTP',
 'B8_phase2',
 'B8_jul',
 'B8_apr',
 'B8A_oct',
 'B8A_apr',
 'B8_INTP',
 'B8A_jul',
 'B7_INTP',
 'B7_jul',
 'B7_oct',
 'B7_phase',
 'B7_phase2',
 'water_INTP',
 'ndwi_apr',
 'ndwi_jul',
 'B8_phase',
 'water_apr',
 'water_jul',
 'water_phase3']

TOPO_bands = [
    'rem',
    'slope',
    'twi',
    'aspect',
    'elevation',
    'hand30_100',
    'hand30_1000',
    'hillshade',
]


climate_bands = [
      'soil_water_0',
       'soil_water_10',
       'soil_water_100',
       'soil_water_200',
       'soil_water_30',
       'soil_water_60',
       'canopy_height',
       'canopy_height_std',
       'era5_precip',
       'chirps_precip',
       'BIOME_NUM',
       'ECO_ID',
]

seasonal_bands = [
  'B11_apr',
 'B11_jul',
 'B11_oct',
 'B12_apr',
 'B12_jul',
 'B12_oct',
 'B2_apr',
 'B2_jul',
 'B2_oct',
 'B3_apr',
 'B3_jul',
 'B3_oct',
 'B4_apr',
 'B4_jul',
 'B4_oct',
 'B5_apr',
 'B5_jul',
 'B5_oct',
 'B6_apr',
 'B6_jul',
 'B6_oct',
 'B7_apr',
 'B7_jul',
 'B7_oct',
 'B8A_apr',
 'B8A_jul',
 'B8A_oct',
 'B8_apr',
 'B8_jul',
 'B8_oct',
 'HH_apr',
 'HH_jul',
 'HH_oct',
 'HV_apr',
 'HV_jul',
 'HV_oct',
 'VH_apr',
 'VH_jul',
 'VH_oct',
 'VV_apr',
 'VV_jul',
 'VV_oct',
 'ndvi_apr',
 'ndvi_jul',
 'ndvi_oct',
 'ndwi_apr',
 'ndwi_jul',
 'ndwi_oct',
 'water_apr',
 'water_jul',
 'water_oct']

S1_coefs = [
    'VH_INTP',
    'VH_SLP',
    'VH_COS',
    'VH_SIN',
    'VH_COS2',
    'VH_SIN2',
    'VH_COS3',
    'VH_SIN3',
    'VV_INTP',
    'VV_SLP',
    'VV_COS',
    'VV_SIN',
    'VV_COS2',
    'VV_SIN2',
    'VV_COS3',
    'VV_SIN3'
]

SS_coefs = [
    'HV_INTP',
    'HV_SLP',
    'HV_COS',
    'HV_SIN',
    'HV_COS2',
    'HV_SIN2',
    'HV_COS3',
    'HV_SIN3',
    'HH_INTP',
    'HH_SLP',
    'HH_COS',
    'HH_SIN',
    'HH_COS2',
    'HH_SIN2',
    'HH_COS3',
    'HH_SIN3'
]

S2_coefs = [
    'ndvi_INTP',
    'ndvi_SLP',
    'ndvi_COS',
    'ndvi_SIN',
    'ndvi_COS2',
    'ndvi_SIN2',
    'ndvi_COS3',
    'ndvi_SIN3',
    'ndwi_INTP',
    'ndwi_SLP',
    'ndwi_COS',
    'ndwi_SIN',
    'ndwi_COS2',
    'ndwi_SIN2',
    'ndwi_COS3',
    'ndwi_SIN3'
]


S1_HM = [
    'VH_INTP',
    'VH_min',
    'VH_max',
    'VH_mean',
    'VH_amp',
    'VH_phase',
    'VH_phase2',
    'VH_phase3',
    'VV_INTP',
    'VV_min',
    'VV_max',
    'VV_mean',
    'VV_amp',
    'VV_phase',
    'VV_phase2',
    'VV_phase3'
]

SS_HM = [
    'HV_INTP',
    'HV_min',
    'HV_max',
    'HV_mean',
    'HV_amp',
    'HV_phase',
    'HV_phase2',
    'HV_phase3',
    'HH_INTP',
    'HH_min',
    'HH_max',
    'HH_mean',
    'HH_amp',
    'HH_phase',
    'HH_phase2',
    'HH_phase3'
]

S2_HM = [
    'ndvi_INTP',
    'ndvi_min',
    'ndvi_max',
    'ndvi_mean',
    'ndvi_amp',
    'ndvi_phase',
    'ndvi_phase2',
    'ndvi_phase3',
    'ndwi_INTP',
    'ndwi_min',
    'ndwi_max',
    'ndwi_mean',
    'ndwi_amp',
    'ndwi_phase',
    'ndwi_phase2',
    'ndwi_phase3'
]

S2_HM_V2 = [
    'ndvi_INTP',
    'ndvi_min',
    'ndvi_max',
    'ndvi_mean',
    'ndvi_amp',
    'ndvi_phase',
    'ndvi_phase2',
    'ndvi_phase3',
    'B12_INTP',
    'B12_min',
    'B12_max',
    'B12_mean',
    'B12_amp',
    'B12_phase',
    'B12_phase2',
    'B12_phase3'
]

label_bands = [
  'fused_label'
  "wetland_label",
  "wetland_mask",
  'world_cover', 
  'GWL_FCS30',
  "cifor",
  "rfw",
]



geo_bands = [
  'idx', 'lat', 'lon', 'geometry'
]


feature_dict = {
  'S1': S1_bands,
  'SS': SS_bands,
  'S2': S2_bands,
  'S2_selected': S2_bands_selected,
  'TOPO': TOPO_bands,
  'Climate': climate_bands,
  'Season': seasonal_bands,

  'S1_coefs': S1_coefs,
  'SS_coefs': SS_coefs,
  'S2_coefs': S2_coefs,

  'S1_HM': S1_HM,
  'SS_HM': SS_HM,
  'S2_HM': S2_HM,
  'S2_HM_V2': S2_HM_V2,

  'label': label_bands,
  'geo': geo_bands,
  
  'RMSE': rmse_bands,
  'ALL': bandList,
}



#%%

def which_sensor(band):
  if ('VH' in band) or ('VV' in band) or ('_s1' in band): sensor = 'S1'
  elif ('HV' in band) or ('HH' in band) or ('_ss' in band): sensor = 'SS'
  elif band in TOPO_bands : sensor = 'TOPO'
  elif band in climate_bands : sensor = 'Climate'
  elif band in S2_bands: sensor = 'S2'
  elif band in label_bands: sensor = 'label'
  elif band in geo_bands: sensor = 'geo'
  elif 'rmse' in band: sensor = 'RMSE'
  else: sensor = band

  return sensor

# sensor_bands = [band for band in bandList if 'S1' == which_sensor(band)]
# print(len(S2_bands) +  len(S1_bands) + len(SS_bands) + len(TOPO_bands) + len(climate_bands) == len(bandList))


#%%
from prettyprinter import pprint

""" Seasonal Synthetic Images """
# seasonal_bands = [band for band in bandList if band.endswith('_apr') or band.endswith('_jul') or band.endswith('_oct')]


""" Coefs """
# postfix_list = ['INTP', 'SLP', 'COS', 'SIN', 'COS2', 'SIN2', 'COS3', 'SIN3']
# sensor_coefs = []
# for band in ['ndvi', 'ndwi']:
#   sensor_coefs += [f"{band}_{postfix}" for postfix in postfix_list]
# pprint(sensor_coefs)  


""" amp, phase, min, max, mean """
# sensor_coefs = []
# for band in ['ndvi', 'B12']:
#   sensor_coefs += [f"{band}_{postfix}" for postfix in ['min', 'max', 'mean', 'amp', 'phase', 'phase2', 'phase3']]
# pprint(sensor_coefs)  